import { useMemo, useState } from 'react';
import { BuilderPanel } from '../components/BuilderPanel';
import { DecisionCenter } from '../components/DecisionCenter';
import { liveEvents } from '../services/liveAdapter';
import { useIntelligence } from '../state/IntelligenceProvider';
import { evaluateDecisionCenter } from '../core/decisionCenter';
import type { OptimizationResult } from '../core/types';

interface Props { selections: import('../domain/types').Selection[]; stake: number; addSelection: (s: import('../domain/types').Selection) => void; removeSelection: (id: string) => void; clear: () => void; updateStake: (v: number) => void; }

export default function BuilderPage({ selections, stake, addSelection, removeSelection, clear, updateStake }: Props) {
  const { dataset, phase, error, runAnalysis, optimizeBuilder, selectedDate } = useIntelligence();
  const [drawerOpen, setDrawerOpen] = useState(false); const [message, setMessage] = useState(''); const [optimization, setOptimization] = useState<OptimizationResult | null>(null);
  const events = useMemo(() => (dataset ? liveEvents(dataset) : []), [dataset]); const decision = useMemo(() => evaluateDecisionCenter(selections), [selections]); const isAdded = (id: string) => selections.some((s) => s.id === id);
  const onAnalyze = async () => { if (!selections.length) return; const eventIds=[...new Set(selections.map((s)=>s.eventId))]; const results=await Promise.all(eventIds.map((eventId)=>runAnalysis(eventId,{depth:'deep'}))); setMessage(`Core Intelligence: ${results.filter(Boolean).length}/${eventIds.length} event analyses completed at deep depth.`); };
  const onOptimize = async () => {
    setOptimization(null);
    if (!selections.length) { setMessage('Decision Gate: blocked — add at least one selection.'); return; }
    if (decision.status === 'BLOCKED') {
      setMessage(`Decision Gate: BLOCKED — resolve ${decision.blockers.length} blocker(s) before Core Engine optimization.`);
      return;
    }
    const result = await optimizeBuilder({decisionGate:{status:decision.status,blockers:decision.blockers,warnings:decision.warnings,trace:decision.trace},stake,minEv:0,maxSelections:8,maxPerCorrelationGroup:1,minConfidence:0.5,selections:selections.map((s)=>({id:s.id,odds:s.odds,probability:s.probability,correlationGroup:s.correlationGroup,confidence:s.confidence,risk:s.risk}))});
    setOptimization(result);
    if(result) setMessage(`Core Optimizer: ${result.selections.length} retained, ${result.rejectedSelections.length} filtered · diversification ${(result.diversificationScore*100).toFixed(0)}%.`);
  };
  if (phase==='loading'&&!dataset) return <main className="mx-auto max-w-[1400px] px-4 py-10 text-slate-300">Loading live builder data…</main>;
  if (phase==='error'&&!dataset) return <main className="mx-auto max-w-[1400px] px-4 py-10"><div className="rounded-2xl border border-red-400/20 bg-red-400/5 p-6 text-slate-300">{error??'Live odds unavailable.'}</div></main>;
  return <main className="mx-auto w-full max-w-[1480px] px-4 py-6 pb-28 md:px-6 md:py-8 md:pb-10">
    <header className="relative overflow-hidden rounded-2xl border border-white/[.08] bg-[#080c13]/80 px-5 py-5 shadow-2xl shadow-black/30 backdrop-blur-xl md:px-7 md:py-6"><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl"/><div className="absolute -left-20 -bottom-24 h-56 w-56 rounded-full bg-cyan-400/5 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.28em] text-violet-300"><span className="live-dot h-1.5 w-1.5 rounded-full bg-emerald-400"/> Core Intelligence Platform</div><h1 className="mt-2 text-3xl font-black tracking-[-.04em] text-white md:text-4xl">Bet Builder <span className="text-slate-600">/</span> Decision Lab</h1><p className="mt-2 max-w-2xl text-xs leading-relaxed text-slate-500 md:text-sm">Build a portfolio. Audit dependencies. Let the Core Engine explain every decision before you act.</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-emerald-400/20 bg-emerald-400/[.06] px-3 py-1.5 text-[9px] font-black uppercase tracking-[.16em] text-emerald-300">{dataset?.mode === 'LIVE' ? 'Live provider' : 'Demo dataset'}</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-[9px] font-black uppercase tracking-[.16em] text-slate-400">{selectedDate}</span></div></div></header>
    {message?<div role="status" className="rise mt-3 rounded-xl border border-violet-400/20 bg-violet-500/[.06] px-4 py-3 text-xs font-medium text-violet-200 shadow-lg shadow-violet-950/10">{message}</div>:null}
    {optimization?<div className="mt-3 grid gap-2 sm:grid-cols-4">{[['Combined odds',optimization.combinedOdds.toFixed(2)],['Estimated EV',`${optimization.estimatedEv>=0?'+':''}${(optimization.estimatedEv*100).toFixed(1)}%`],['Probability',`${(optimization.estimatedProbability*100).toFixed(1)}%`],['Diversification',`${(optimization.diversificationScore*100).toFixed(0)}%`]].map(([label,value])=><div key={label} className="glass rounded-xl p-3"><div className="text-[8px] font-bold uppercase tracking-[.16em] text-slate-600">{label}</div><div className="mt-1 text-lg font-black text-white">{value}</div></div>)}</div>:null}
    <DecisionCenter result={decision} optimization={optimization} selections={selections}/>
    <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]"><section aria-label="Events" className="glass rounded-2xl p-4 md:p-5"><div className="flex items-end justify-between border-b border-white/[.08] pb-3"><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-violet-300">Market board</div><h2 className="mt-1 text-lg font-black text-white">Live Events</h2></div><span className="font-mono text-[9px] text-slate-600">{events.length} EVENTS</span></div><div className="mt-4 space-y-3">
      {events.map((e,index)=><article key={e.id} className="rise group rounded-xl border border-white/[.07] bg-white/[.025] p-4 transition duration-300 hover:-translate-y-0.5 hover:border-violet-400/20 hover:bg-white/[.045] hover:shadow-xl hover:shadow-black/20" style={{animationDelay:`${Math.min(index*35,350)}ms`}}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.6)]"/><div className="truncate text-sm font-bold text-white">{e.homeTeam} <span className="text-slate-600">vs</span> {e.awayTeam}</div></div><div className="mt-1 pl-3.5 text-[9px] font-bold uppercase tracking-[.16em] text-slate-600">{e.sport} · {e.league}</div></div><div className="shrink-0 rounded-lg border border-white/[.06] bg-black/10 px-2.5 py-1.5 text-[10px] font-mono text-slate-500">{new Date(e.startTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div><div className="mt-3 flex flex-wrap gap-1.5">{e.markets.flatMap((m)=>m.selections).map((s)=>{const added=isAdded(s.id); return <button key={s.id} type="button" aria-pressed={added} onClick={()=>added?removeSelection(s.id):addSelection(s)} className={`group/btn rounded-lg border px-2.5 py-2 text-[10px] font-bold transition-all duration-200 ${added?'border-violet-400/50 bg-violet-500/20 text-violet-100 shadow-[0_0_18px_rgba(124,92,255,.10)]':'border-white/[.08] bg-black/10 text-slate-400 hover:border-violet-400/30 hover:bg-violet-400/[.07] hover:text-white'}`}><span>{s.shortName}</span><span className="ml-1.5 font-mono text-violet-300/90">{s.odds.toFixed(2)}</span></button>;})}</div></article>)}
      {!events.length?<div className="rounded-xl border border-dashed border-white/10 p-10 text-center text-xs text-slate-500">No live provider events for {selectedDate}.</div>:null}</div></section><div className="hidden lg:block"><div className="sticky top-6 h-[calc(100vh-48px)]"><BuilderPanel selections={selections} stake={stake} onUpdateStake={updateStake} onClear={clear} onRemove={removeSelection} onAnalyze={()=>void onAnalyze()} onOptimize={()=>void onOptimize()} feedMode={dataset?.mode ?? 'UNKNOWN'}/></div></div></div>
    <div className="lg:hidden"><button type="button" onClick={()=>setDrawerOpen(true)} className="fixed bottom-[64px] inset-x-3 z-40 rounded-2xl border border-violet-400/25 bg-[#0b1018]/95 p-3.5 text-left shadow-2xl shadow-black/50 backdrop-blur-xl"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold text-white">{selections.length} selection(s)</span><span className="rounded-lg bg-violet-500/15 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-violet-200">Open Builder</span></div></button></div>
    {drawerOpen?<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={()=>setDrawerOpen(false)} aria-hidden/><div className="absolute inset-x-0 bottom-0 max-h-[88vh] overflow-y-auto rounded-t-3xl border-t border-white/10 bg-[#080c13] p-3 pb-6 shadow-2xl"><div className="mb-3 flex items-center justify-between px-1"><div className="text-xs font-black uppercase tracking-[.2em] text-white">Bet Builder</div><button type="button" aria-label="Close builder" onClick={()=>setDrawerOpen(false)} className="rounded-lg border border-white/10 px-2.5 py-1 text-slate-400">✕</button></div><BuilderPanel selections={selections} stake={stake} onUpdateStake={updateStake} onClear={clear} onRemove={removeSelection} onAnalyze={()=>void onAnalyze()} onOptimize={()=>void onOptimize()}/></div></div>:null}
  </main>;
}
