import {useMemo,useState} from 'react';
import {Sparkles,RefreshCw,ShieldCheck,Target,WalletCards,BrainCircuit} from 'lucide-react';
import {useIntelligence} from '../state/IntelligenceProvider';
import {liveEvents} from '../services/liveAdapter';
import {generateCoupon,type CouponMode,type CouponResult} from '../core/couponEngine';
import {evaluateRiskPolicy} from '../core/riskPolicy';

const WARNING_COPY:Record<string,string>={
 NEGATIVE_EV:'Brak przewagi: kursy są poniżej uczciwej wyceny rynku (marża bukmachera). Długoterminowo taki kupon traci.',
 TARGET_NOT_REACHED:'Nie udało się trafić w docelowy kurs z dostępnych wydarzeń — pokazano najbliższy możliwy.',
 ZERO_STAKE:'Stawka wynosi 0 PLN.',
};
function couponMessage(c:CouponResult){
 if(c.blockers.includes('NO_VALUE_SELECTIONS'))return `Brak typów z przewagą (EV > 0) w aktualnym feedzie. Przełącz na „Najlepsze dostępne kursy” albo odśwież dane później.`;
 if(c.blockers.includes('NO_QUALIFIED_SELECTIONS'))return `Żadne wydarzenie nie spełnia filtrów (kurs 1.20–6.00, pewność danych). Pula: ${c.poolSize}.`;
 if(c.blockers.includes('TARGET_ODDS_INVALID'))return 'Podaj docelowy kurs większy niż 1.';
 return 'Kupon zablokowany: '+c.blockers.join(', ');
}

export default function CouponLabPage(){
 const {dataset,selectedDate,refresh,runAnalysis,phase}=useIntelligence();
 const [target,setTarget]=useState('50'); const [stake,setStake]=useState('20'); const [result,setResult]=useState<CouponResult|null>(null); const [ai,setAi]=useState<Record<string,'loading'|'ok'|'failed'>>({}); const [message,setMessage]=useState(''); const [mode,setMode]=useState<CouponMode>('BEST_AVAILABLE'); const [excluded,setExcluded]=useState<string[]>([]);
 const events=useMemo(()=>dataset?liveEvents(dataset):[],[dataset]);
 const generate=async(opts:{target?:string;mode?:CouponMode;exclude?:string[]}={})=>{if(!dataset){setMessage('Brak datasetu danych. Odśwież źródło.');return;} const numericTarget=Number(opts.target??target),numericStake=Number(stake); const coupon=generateCoupon({events,targetOdds:numericTarget,stake:numericStake,tolerance:.2,maxLegs:10,minLegOdds:1.2,maxLegOdds:6,minConfidence:.5,mode:opts.mode??mode,excludeEventIds:opts.exclude??[]}); setExcluded(opts.exclude??[]); setResult(coupon); if(coupon.status==='BLOCKED'){setMessage(couponMessage(coupon));return;} const next:Record<string,'loading'|'ok'|'failed'>={}; coupon.legs.forEach(l=>next[l.eventId]='loading');setAi(next); setMessage('Core Engine AI analizuje '+coupon.legs.length+' wybranych wydarzeń…'); await Promise.all(coupon.legs.map(async leg=>{try{const analysis=await runAnalysis(leg.eventId,{depth:'deep'});setAi(p=>({...p,[leg.eventId]:analysis?'ok':'failed'}));}catch{setAi(p=>({...p,[leg.eventId]:'failed'}));}})); setMessage('Analiza zakończona. Wynik kuponu pozostaje oznaczony jako modelowy i wymaga weryfikacji wyniku.');};
 const policy=result&&evaluateRiskPolicy({selections:result.legs.map(l=>({id:l.selectionId,marketId:l.marketId,eventId:l.eventId,name:l.label,shortName:l.label,odds:l.marketOdds,probability:l.probability,impliedProbability:1/l.marketOdds,value:l.edge,ev:l.ev,confidence:l.confidence,risk:l.risk,correlationGroup:l.marketId})),dataFreshness:dataset?.providerHealth?Math.max(0,1-dataset.providerHealth.ageSeconds/Math.max(1,dataset.providerHealth.staleAfterSeconds)):0,evidenceQuality:dataset?.providerHealth?.state==='HEALTHY'?.8:.5,providerState:dataset?.providerHealth?.state??'OFFLINE'});
 if(phase==='loading'&&!dataset)return <div className="mx-auto max-w-[1200px] px-5 py-12 text-slate-400">Ładowanie danych sportowych…</div>;
 return <main className="mx-auto w-full max-w-[1380px] px-4 py-6 md:px-6 md:py-8">
  <section className="glass-strong overflow-hidden rounded-3xl border border-violet-400/20 p-5 md:p-8">
   <div className="flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.24em] text-violet-300"><Sparkles size={13}/> Core Engine · Coupon Lab</div><h1 className="mt-2 text-3xl font-black text-white md:text-5xl">Generator kuponu</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Pobierz aktualne wydarzenia i kursy, zastosuj ranking predykcyjny, wybierz rozdzielone zdarzenia pod zadany kurs i przelicz potencjalny zwrot.</p></div><button type="button" onClick={()=>void refresh(selectedDate,true)} className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2.5 text-xs font-bold text-white"><RefreshCw size={14} className="mr-2 inline"/>Odśwież dane</button></div>
   <div className="mt-7 grid gap-3 md:grid-cols-4">
    <label className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">Docelowy kurs<div className="mt-1.5 flex items-center rounded-xl border border-violet-400/25 bg-black/20 px-3"><Target size={14} className="text-violet-300"/><input value={target} onChange={e=>setTarget(e.target.value)} type="number" min="1.01" step="0.01" className="w-full bg-transparent px-2 py-3 text-lg font-black text-white outline-none"/></div></label>
    <label className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">Stawka<div className="mt-1.5 flex items-center rounded-xl border border-amber-400/20 bg-black/20 px-3"><WalletCards size={14} className="text-amber-300"/><input value={stake} onChange={e=>setStake(e.target.value)} type="number" min="0" step="0.01" className="w-full bg-transparent px-2 py-3 text-lg font-black text-white outline-none"/><span className="text-xs text-slate-600">PLN</span></div></label>
    <div className="md:col-span-2"><div className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">Szybki cel</div><div className="mt-1.5 grid grid-cols-5 gap-2">{['5','10','50','100','150'].map(v=><button key={v} type="button" onClick={()=>{setTarget(v);if(result)void generate({target:v});}} className={target===v?'rounded-xl border border-violet-300/50 bg-violet-400/15 py-3 text-sm font-black text-violet-100':'rounded-xl border border-white/10 bg-white/[.03] py-3 text-sm font-bold text-slate-300 hover:bg-white/[.06]'}>x{v}</button>)}</div></div>
   </div>
   <button type="button" onClick={()=>void generate()} disabled={!dataset} className="mt-5 w-full rounded-2xl border border-violet-300/30 bg-violet-500/15 px-5 py-4 text-sm font-black text-white shadow-[0_0_40px_rgba(120,80,255,.12)]"><BrainCircuit size={17} className="mr-2 inline"/>ANALIZUJ I GENERUJ KUPON</button>
   <div className="mt-3 flex flex-wrap items-center gap-2" role="group" aria-label="Tryb doboru typów">{([['BEST_AVAILABLE','Najlepsze dostępne kursy'],['VALUE_ONLY','Tylko z przewagą (EV > 0)']] as const).map(([m,l])=><button key={m} type="button" aria-pressed={mode===m} onClick={()=>{setMode(m);if(result)void generate({mode:m});}} className={mode===m?'min-h-[44px] rounded-xl border border-cyan-300/40 bg-cyan-400/10 px-3 text-xs font-bold text-cyan-100':'min-h-[44px] rounded-xl border border-white/10 bg-white/[.03] px-3 text-xs font-bold text-slate-400'}>{l}</button>)}{result&&result.legs.length>0&&<button type="button" onClick={()=>void generate({exclude:[...excluded,...result.legs.map(l=>l.eventId)]})} className="min-h-[44px] rounded-xl border border-white/10 bg-white/[.03] px-3 text-xs font-bold text-slate-300">Losuj inny zestaw</button>}{excluded.length>0&&<button type="button" onClick={()=>void generate({exclude:[]})} className="min-h-[44px] rounded-xl px-3 text-xs font-bold text-slate-500 underline">Wróć do najlepszego</button>}</div>
   {message&&<div role="status" className="mt-3 rounded-xl border border-white/[.08] bg-white/[.025] px-4 py-3 text-xs text-slate-300">{message}</div>}
  </section>
  {result&&<section className="mt-5 grid gap-4 lg:grid-cols-[1.5fr_.7fr]">
   <div className="glass rounded-2xl border border-white/[.08] p-4 md:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-violet-300">Wygenerowany kupon · {selectedDate}</div><h2 className="mt-1 text-2xl font-black text-white">Kurs {result.combinedOdds.toFixed(2)} <span className="text-sm font-bold text-slate-500">/ cel {result.targetOdds.toFixed(2)}</span></h2><div className="mt-1 text-[11px] text-slate-500">Pula: {result.poolSize} wydarzeń · {result.valuePoolSize} typów z przewagą nad rynkiem</div></div><span className={result.status==='READY'?'rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[9px] font-black text-emerald-300':result.status==='REVIEW'?'rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1.5 text-[9px] font-black text-amber-300':'rounded-full border border-red-400/20 bg-red-400/10 px-3 py-1.5 text-[9px] font-black text-red-300'}>{result.status}</span></div>
    <div className="mt-4 space-y-2">{result.legs.map((leg,i)=><article key={leg.selectionId} className="rounded-xl border border-white/[.07] bg-white/[.025] p-3"><div className="flex items-start gap-3"><span className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-violet-400/10 text-[10px] font-black text-violet-300">{i+1}</span><div className="min-w-0 flex-1"><div className="text-sm font-bold text-white">{leg.eventLabel}</div><div className="mt-1 text-xs text-slate-400">{leg.label} · {leg.league}</div><div className="mt-2 flex flex-wrap gap-2 text-[9px] font-bold"><span className="rounded-full bg-white/[.04] px-2 py-1 text-amber-200">kurs {leg.marketOdds.toFixed(2)}</span><span className="rounded-full bg-white/[.04] px-2 py-1 text-emerald-300">EV {(leg.ev*100).toFixed(1)}%</span><span className="rounded-full bg-white/[.04] px-2 py-1 text-violet-300">conf. {(leg.confidence*100).toFixed(0)}%</span><span className="rounded-full bg-white/[.04] px-2 py-1 text-slate-400">{ai[leg.eventId]==='loading'?'AI ANALYZING':ai[leg.eventId]==='ok'?'AI VERIFIED':'AI REVIEW'}</span></div></div></div></article>)}</div>
   </div>
   <aside className="space-y-3"><div className="ai-surface rounded-2xl p-5"><div className="text-[9px] font-black uppercase tracking-[.18em] text-violet-300">Potencjalna wypłata</div><div className="mt-2 text-4xl font-black text-white">{result.potentialReturn.toFixed(2)} PLN</div><div className="mt-1 text-xs text-emerald-300">zysk brutto {result.potentialProfit.toFixed(2)} PLN</div><div className="mt-4 grid grid-cols-2 gap-3"><div><div className="text-[8px] uppercase text-slate-600">Prawdopodobieństwo</div><div className="mt-1 text-lg font-black text-white">{(result.estimatedProbability*100).toFixed(1)}%</div></div><div><div className="text-[8px] uppercase text-slate-600">Model EV</div><div className="mt-1 text-lg font-black text-white">{(result.estimatedEv*100).toFixed(1)}%</div></div></div></div>
    <div className="glass rounded-2xl p-4"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.18em] text-emerald-300"><ShieldCheck size={13}/> Risk / Policy</div><div className="mt-2 text-sm font-bold text-white">{policy?.decision??'WAIT'}</div><div className="mt-2 text-[10px] leading-5 text-slate-500">{policy?.trace.join(' ')??'Brak oceny.'}</div></div>
    {result.warnings.length>0&&<div className="rounded-2xl border border-amber-400/20 bg-amber-400/[.05] p-4 text-xs leading-5 text-amber-200">{result.warnings.map(w=>WARNING_COPY[w]??w).join(' ')}</div>}
   </aside>
  </section>}
  <div className="mt-5 grid gap-3 md:grid-cols-3"><div className="glass rounded-xl p-4"><div className="text-[8px] font-black uppercase tracking-[.16em] text-slate-600">Źródło danych</div><div className="mt-1 text-sm font-bold text-white">{dataset?.provider??'—'}</div><div className="mt-1 text-[10px] text-slate-500">{dataset?.mode??'—'} · {dataset?.events.length??0} events · {dataset?.snapshots.length??0} snapshots</div></div><div className="glass rounded-xl p-4"><div className="text-[8px] font-black uppercase tracking-[.16em] text-slate-600">Core Engine</div><div className="mt-1 text-sm font-bold text-white">CONTEXT → INTELLIGENCE → DECISION</div><div className="mt-1 text-[10px] text-slate-500">Predykcja nie jest gwarancją wyniku.</div></div><div className="glass rounded-xl p-4"><div className="text-[8px] font-black uppercase tracking-[.16em] text-slate-600">Weryfikacja</div><div className="mt-1 text-sm font-bold text-white">OUTCOME → LEARNING</div><div className="mt-1 text-[10px] text-slate-500">Kupony muszą być śledzone po zakończeniu wydarzeń.</div></div></div>
 </main>;
}
