import type { DeterministicNumber, MarketKey } from '../domain/types';
import type { QualityGrade } from '../domain/services/dataQualityService';
import type { CorrelationLevel, RiskLevel } from '../domain/services/riskService';
import type { ValueTier } from '../domain/services/valueService';
import type { MovementDirection, MovementPoint } from '../domain/services/movementService';

export type StatementOrigin = 'ai-inference' | 'deterministic';
export type AnalysisStance = 'constructive' | 'neutral' | 'cautious' | 'avoid';
export type ConfidenceBand = 'very-low' | 'low' | 'medium' | 'high' | 'very-high';
/**
 * Distinguishes a market-backed analysis from an event-level analysis that ran
 * on real provider event data with no bookmaker odds available. The latter must
 * never carry odds-derived conclusions, prices or probabilities.
 */
export type AnalysisDataStatus = 'ODDS_AVAILABLE' | 'INSUFFICIENT_ODDS_DATA';
export interface AnalysisRequest { eventId: string; market?: MarketKey; selectionId?: string; requestedBy: string; depth?: 'standard' | 'deep'; }
export interface AnalysisSummary { headline: string; narrative: string[]; stance: AnalysisStance; origin: 'ai-inference'; groundedIn: string[]; }
export interface ConfidenceAssessment { score: DeterministicNumber; band: ConfidenceBand; rationale: string; origin: 'ai-inference'; drivers: Array<{ label: string; impact: 'increases' | 'decreases'; magnitude: DeterministicNumber }>; }
export interface DataQualityAssessment { grade: QualityGrade; score: DeterministicNumber; freshnessMinutes: DeterministicNumber; bookmakerCoverage: DeterministicNumber; completeness: DeterministicNumber; dispersion: DeterministicNumber; stale: boolean; partial: boolean; issues: Array<{ severity: 'info' | 'warning' | 'error'; message: string }>; interpretation: string; origin: 'ai-inference'; }
export interface KeyFactor { id: string; label: string; detail: string; weight: DeterministicNumber; polarity: 'supportive' | 'adverse' | 'neutral'; origin: StatementOrigin; }
export interface Signal { id: string; label: string; detail: string; strength: DeterministicNumber; origin: StatementOrigin; }
export interface MarketObservation { id: string; selectionId: string; label: string; openingPrice: DeterministicNumber; currentPrice: DeterministicNumber; changePct: DeterministicNumber; volatility: DeterministicNumber; direction: MovementDirection; steam: boolean; lastMoveAt: string; bookCount: DeterministicNumber; series: MovementPoint[]; note: string; origin: 'deterministic'; }
export interface ProbabilityEstimate { selectionId: string; label: string; modelProbability: DeterministicNumber; impliedProbability: DeterministicNumber; fairProbability: DeterministicNumber; modelFairOdds: DeterministicNumber; divergencePct: DeterministicNumber; modelVersion: string; drivers: Array<{ label: string; contribution: DeterministicNumber }>; origin: 'deterministic'; }
export interface ValueSignal { selectionId: string; label: string; bestBookmaker: string | null; bestPrice: DeterministicNumber; consensusPrice: DeterministicNumber; edgePct: DeterministicNumber; qualityAdjustedEdgePct: DeterministicNumber; evPerUnit: DeterministicNumber; kellyFraction: DeterministicNumber; tier: ValueTier; commentary: string; origin: StatementOrigin; }
export interface RiskAssessment { level: RiskLevel; score: DeterministicNumber; exposureCeilingPct: DeterministicNumber; timeToStartMinutes: DeterministicNumber; factors: Array<{ id: string; label: string; weight: DeterministicNumber; score: DeterministicNumber; note: string }>; interpretation: string; origin: StatementOrigin; }
export interface CorrelationAssessment { level: CorrelationLevel; score: DeterministicNumber; independentExposureCount: DeterministicNumber; clusters: Array<{ id: string; label: string; reason: string; strength: DeterministicNumber; relatedEventIds: string[] }>; interpretation: string; origin: StatementOrigin; }
export type RecommendedActionKind = 'MONITOR_MARKET' | 'REASSESS_ON_MOVEMENT' | 'DATA_QUALITY_WATCH' | 'VALUE_CONFIRMATION' | 'CORRELATION_GUARD' | 'NO_ACTION';
export interface RecommendedAction { id: string; kind: RecommendedActionKind; title: string; detail: string; priority: 'low' | 'medium' | 'high'; missionEligible: boolean; trigger?: { metric: 'odds-change-pct' | 'data-quality-score' | 'time-to-start-minutes' | 'edge-pct'; comparator: 'gte' | 'lte'; threshold: DeterministicNumber }; origin: 'ai-inference'; }
export interface AnalysisWarning { id: string; severity: 'info' | 'warning' | 'critical'; message: string; origin: StatementOrigin; }
export interface Assumption { id: string; statement: string; basis: 'model' | 'market' | 'data-pipeline' | 'operational'; confidence: DeterministicNumber; origin: 'ai-inference'; }
export interface SourceSnapshotRef { snapshotId: string; bookmaker: string; market: MarketKey; capturedAt: string; quoteCount: DeterministicNumber; feedLatencyMs: DeterministicNumber; provider: string; }
export interface QuantDecisionPacket { decisionGate: import('../core/types').DecisionGateInput; generatedAt: string; marketSignals: Array<{ selectionId: string; odds: number; impliedProbability: number; fairProbability: number; value: number; ev: number; confidence: number; qualityScore: number; signal: string; fairProbabilitySource: 'MODEL' | 'DEVIG_CONSENSUS' | 'MARKET_IMPLIED' }>; candidates: Array<{ id: string; eventId: string; marketId?: string; odds: number; probability: number; ev?: number; qualityScore?: number; correlationGroup?: string; label?: string }>; portfolio: { selected: string[]; rejected: Array<{ id: string; reason: string }>; combinedOdds: number; baseProbability: number; adjustedProbability: number; estimatedEv: number; dependencyMultiplier: number }; coreOptimization: { selected: string[]; rejected: string[]; combinedOdds: number; estimatedProbability: number; estimatedEv: number; diversificationScore: number; rationale: string }; dependencies: { conflicts: string[]; concentrationPenalty: number; correlationPenalty: number; adjustedJointProbabilityMultiplier: number }; steam: Array<{ selectionId: string; bookmakerCount: number; downCount: number; upCount: number; consensusChangePct: number; strength: string; direction: string }>; methodology: string[]; }
export interface AnalysisMeta { engine: string; engineMode: 'mock' | 'core-engine'; modelVersion: string; contractVersion: string; computeMs: DeterministicNumber; deterministicInputsDigest: string; partial: boolean; degradedReasons: string[]; dataStatus: AnalysisDataStatus; oddsAvailable: boolean; }
export interface AnalysisResponse { analysisId: string; eventId: string; generatedAt: string; summary: AnalysisSummary; confidence: ConfidenceAssessment; dataQuality: DataQualityAssessment; keyFactors: KeyFactor[]; positiveSignals: Signal[]; negativeSignals: Signal[]; marketObservations: MarketObservation[]; probabilityEstimates: ProbabilityEstimate[]; valueSignals: ValueSignal[]; riskAssessment: RiskAssessment; correlationAssessment: CorrelationAssessment; recommendedActions: RecommendedAction[]; warnings: AnalysisWarning[]; assumptions: Assumption[]; sourceSnapshots: SourceSnapshotRef[]; quantDecision?: QuantDecisionPacket; context: { eventLabel: string; leagueName: string; sportLabel: string; market: MarketKey | null; marketLabel: string; startTime: string; status: string }; meta: AnalysisMeta; }
export const ANALYSIS_CONTRACT_VERSION = '3.2.0';
