import { useEffect, useRef, useState, type ReactNode } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { Activity, BarChart3, Clock3, History, LayoutDashboard, ListChecks, Moon, RefreshCw, Sun, Volume2, VolumeX, Zap, ShieldCheck, Target } from 'lucide-react';
import { useIntelligence } from '../state/IntelligenceProvider';
import { cx, relativeTime } from '../lib/format';
import { LANGS, type Lang, applyLanguage, detectBrowserLang } from '../i18n';
import { DecisionLifecycle } from './DecisionLifecycle';
const NAV = [{to:'/',label:'Home',icon:LayoutDashboard,key:'h',end:true},{to:'/live',label:'Live',icon:Activity,key:'l',end:false},{to:'/sports',label:'Sports',icon:ListChecks,key:'s',end:false},{to:'/analysis',label:'Analiza',icon:BarChart3,key:'a',end:false},{to:'/builder',label:'Coupon Lab',icon:Target,key:'b',end:false},{to:'/missions',label:'Misje',icon:Clock3,key:'m',end:false},{to:'/history',label:'Historia',icon:History,key:'i',end:false}];
function Controls(){const [lang,setLang]=useState<Lang>(()=>detectBrowserLang());const [light,setLight]=useState(false);const [sound,setSound]=useState(()=>localStorage.getItem('bb-sound')==='on');useEffect(()=>{applyLanguage(lang);localStorage.setItem('bb-lang',lang)},[lang]);return <div className="flex items-center gap-1">{LANGS.map(x=><button key={x.id} type="button" onClick={()=>setLang(x.id)} className={cx('min-h-[34px] rounded-md px-2 text-[9px] font-bold',lang===x.id?'bg-white/10 text-white':'text-slate-500 hover:text-white')}>{x.label}</button>)}<button type="button" aria-label="Motyw" onClick={()=>{setLight(v=>!v);document.documentElement.dataset.theme=!light?'light':'dark'}} className="grid min-h-[34px] min-w-[34px] place-items-center rounded-md text-slate-400 hover:bg-white/5 hover:text-white">{light?<Moon size={14}/>:<Sun size={14}/>}</button><button type="button" aria-label="Dźwięk" onClick={()=>{setSound(v=>!v);localStorage.setItem('bb-sound',!sound?'on':'off')}} className="hidden sm:grid min-h-[34px] min-w-[34px] place-items-center rounded-md text-slate-400 hover:bg-white/5 hover:text-white">{sound?<Volume2 size={14}/>:<VolumeX size={14}/>}</button></div>}
export function AppShell({children}:{children:ReactNode}){const {dataset,phase,refresh,lastRefreshedAt,nowTick}=useIntelligence();const navigate=useNavigate();const pending=useRef(false);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;if(e.key.toLowerCase()==='g'){pending.current=true;window.setTimeout(()=>pending.current=false,900);return}if(pending.current){const n=NAV.find(x=>x.key===e.key.toLowerCase());if(n){e.preventDefault();navigate(n.to)}pending.current=false}if(e.key.toLowerCase()==='r'&&!e.ctrlKey&&!e.metaKey)void refresh()};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[navigate,refresh]);const live=dataset?.events.filter(e=>e.status==='live').length??0;const mode=dataset?.mode??'SYNC';const age=dataset?(nowTick-new Date(dataset.normalizedAt).getTime())/60000:0;return <div className="bb-shell"><header className="bb-topbar"><div className="bb-topbar-inner"><NavLink to="/" className="bb-brand"><span className="bb-brand-mark"><Zap size={15}/></span><span><span className="bb-brand-name">BET BUILDER</span><span className="bb-brand-sub">SPORTS INTELLIGENCE · DECISION CENTER</span></span></NavLink><nav className="bb-nav" aria-label="Główna nawigacja">{NAV.map(n=><NavLink key={n.to} to={n.to} end={n.end} className={({isActive})=>isActive?'active':''}><n.icon size={13}/>{n.label}<kbd className="hidden xl:inline text-[7px] text-slate-600">{n.key}</kbd></NavLink>)}</nav><div className="bb-status"><span className="bb-status-dot"/>{mode==='LIVE'?'LIVE DATA':mode==='DEMO'?'DEMO MODE':mode} · {live} LIVE</div><Controls/><button type="button" onClick={()=>void refresh()} aria-label="Odśwież dane" className="grid min-h-[34px] min-w-[34px] place-items-center rounded-md border border-white/10 text-slate-400 hover:text-white"><RefreshCw size={13} className={phase==='loading'?'animate-spin':''}/></button></div></header><main className="bb-workspace"><DecisionLifecycle/><div className="mb-4 flex items-center justify-between gap-3 text-[8px] font-mono uppercase tracking-[.12em] text-slate-600"><span className="flex items-center gap-2"><ShieldCheck size={11} className="text-emerald-400"/> Human approval required before execution</span><span>{lastRefreshedAt?'Sync '+relativeTime(lastRefreshedAt,nowTick):age>0?'Data '+Math.round(age)+'m':'Syncing…'}</span></div>{children}</main></div>}
