import type { DecisionCenterResult } from '../core/decisionCenter';
import type { OptimizationResult } from '../core/types';
import type { Selection } from '../domain/types';

function pct(v:number){return `${(v*100).toFixed(0)}%`;}
function tone(status:DecisionCenterResult['status']){return status==='READY'?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':status==='CAUTION'?'border-amber-400/30 bg-amber-400/10 text-amber-300':'border-red-400/30 bg-red-400/10 text-red-300';}
function delta(v:number,digits=1){return `${v>=0?'+':''}${v.toFixed(digits)}`;}

export function DecisionCenter({result,optimization,selections}:{result:DecisionCenterResult;optimization?:OptimizationResult|null;selections:Selection[]}){
 const selectedIds=new Set(optimization?.selections??[]); const optimized=optimization?selections.filter(s=>selectedIds.has(s.id)):[]; const removed=optimization?selections.filter(s=>!selectedIds.has(s.id)):[];
 const rejected=optimization?optimization.rejectedSelections.map(id=>({selection:selections.find(s=>s.id===id),reason:optimization.rejectedReasons[id]??'Rejected by optimizer constraints.'})).filter((x):x is {selection:Selection;reason:string}=>Boolean(x.selection)):[];
 const oddsDelta=optimization?optimization.combinedOdds-result.combinedOdds:0; const probabilityDelta=optimization?optimization.estimatedProbability-result.adjustedProbability:0; const evDelta=optimization?optimization.estimatedEv-result.ev:0;
 const metrics=[['Odds',result.combinedOdds.toFixed(2)],['Probability',pct(result.adjustedProbability)],['EV',`${result.ev>=0?'+':''}${(result.ev*100).toFixed(1)}%`],['Confidence',pct(result.confidence)],['Quality',pct(result.quality)],['Dependency',result.dependencyMultiplier.toFixed(3)]];
 return <section className="glass-strong glow-ai rise mt-5 overflow-hidden rounded-2xl" aria-label="Core Engine Decision Center">
  <div className="relative border-b border-white/[.08] p-4 md:p-5"><div className="absolute right-0 top-0 h-32 w-56 bg-violet-500/10 blur-3xl"/><div className="relative flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.25em] text-violet-300"><span className="h-1.5 w-1.5 rounded-full bg-violet-300 shadow-[0_0_12px_rgba(167,139,250,.8)]"/> Core Engine · Decision Center 2.0</div><h2 className="mt-1 text-xl font-black tracking-[-.03em] text-white md:text-2xl">Portfolio Decision Packet</h2><p className="mt-1 max-w-xl text-[11px] leading-relaxed text-slate-500">Audit, dependency analysis and optimizer output in one decision surface.</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/10 bg-white/[.03] px-2.5 py-1.5 text-[9px] font-black tracking-wider text-slate-500">{optimization?'OPTIMIZER SYNCED':'AUDIT ONLY'}</span><span className={`rounded-full border px-3 py-1.5 text-[10px] font-black tracking-[.12em] ${tone(result.status)}`}>{result.status}</span></div></div></div>
  <div className="grid grid-cols-2 gap-px bg-white/[.045] md:grid-cols-6">{metrics.map(([label,value],i)=><div key={label} className="bg-[#090e16] p-3.5 md:p-4"><div className="text-[8px] font-bold uppercase tracking-[.18em] text-slate-600">{label}</div><div className={`mt-1.5 text-base font-black ${i===2&&result.ev>=0?'text-emerald-300':'text-white'}`}>{value}</div></div>)}</div>
  {optimization?<div className="border-y border-violet-400/10 bg-violet-500/[.035] p-4 md:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-[10px] font-black uppercase tracking-[.18em] text-violet-300">Engine delta</h3><div className="mt-1 text-[10px] text-slate-600">Submitted portfolio → optimized portfolio</div></div><div className="flex flex-wrap gap-1.5 text-[9px] font-bold"><span className="rounded-md border border-white/10 bg-black/10 px-2 py-1 text-slate-500">Δ odds {delta(oddsDelta,2)}</span><span className="rounded-md border border-white/10 bg-black/10 px-2 py-1 text-slate-500">Δ probability {delta(probabilityDelta*100)}pp</span><span className="rounded-md border border-white/10 bg-black/10 px-2 py-1 text-slate-500">Δ EV {delta(evDelta*100)}pp</span></div></div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-5">{[['Legs',`${selections.length} → ${optimized.length}`],['Odds',`${result.combinedOdds.toFixed(2)} → ${optimization.combinedOdds.toFixed(2)}`],['Probability',`${pct(result.adjustedProbability)} → ${pct(optimization.estimatedProbability)}`],['EV',`${delta(result.ev*100)}% → ${delta(optimization.estimatedEv*100)}%`],['Diversification',pct(optimization.diversificationScore)]].map(([label,value])=><div key={label} className="rounded-xl border border-white/[.07] bg-black/15 p-2.5"><div className="text-[8px] uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 text-xs font-black text-white">{value}</div></div>)}</div></div>:null}
  <div className="grid gap-4 p-4 md:p-5 lg:grid-cols-[1.15fr_.85fr]">
   <div className="rounded-xl border border-white/[.07] bg-black/10 p-3"><div className="mb-3 flex items-center justify-between"><div><h3 className="text-[9px] font-black uppercase tracking-[.18em] text-slate-400">Leg audit</h3><div className="mt-0.5 text-[9px] text-slate-600">Edge · EV · confidence</div></div><span className="font-mono text-[9px] text-slate-600">{result.legDecisions.length} LEGS</span></div><div className="space-y-1.5">{result.legDecisions.map(leg=>{const kept=!optimization||selectedIds.has(leg.selection.id);return <div key={leg.selection.id} className={`grid grid-cols-[auto_1fr_auto_auto] items-center gap-2 rounded-lg border p-2.5 transition ${kept?'border-white/[.05] bg-white/[.02]':'border-red-400/10 bg-red-400/[.025]'}`}><span className={`rounded-md px-1.5 py-1 text-[8px] font-black ${kept?'bg-emerald-400/10 text-emerald-300':'bg-red-400/10 text-red-300'}`}>{kept?'KEEP':'DROP'}</span><div className="min-w-0"><div className="truncate text-[11px] font-semibold text-slate-100">{leg.selection.shortName}</div><div className="mt-0.5 text-[9px] text-slate-600">implied {pct(leg.implied)} · {leg.risk} risk</div></div><div className={`text-[10px] font-black ${leg.edge>=0?'text-emerald-300':'text-red-300'}`}>{leg.edge>=0?'+':''}{(leg.edge*100).toFixed(1)}%</div><div className="text-[10px] font-bold text-slate-400">{pct(leg.confidence)}</div></div>})}</div></div>
   <div className="space-y-2">{result.blockers.length?<div className="rounded-xl border border-red-400/15 bg-red-400/[.045] p-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-red-300">Blockers</div>{result.blockers.map(x=><div key={x} className="mt-1 text-[10px] leading-relaxed text-red-200/80">{x}</div>)}</div>:null}{result.warnings.length?<div className="rounded-xl border border-amber-400/15 bg-amber-400/[.045] p-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-amber-300">Warnings</div>{result.warnings.map(x=><div key={x} className="mt-1 text-[10px] leading-relaxed text-amber-200/80">{x}</div>)}</div>:null}{result.strengths.length?<div className="rounded-xl border border-emerald-400/15 bg-emerald-400/[.045] p-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-300">Signals</div>{result.strengths.map(x=><div key={x} className="mt-1 text-[10px] leading-relaxed text-emerald-200/80">{x}</div>)}</div>:null}</div>
  </div>
  {optimization?<div className="grid gap-3 border-t border-white/[.07] p-4 md:p-5 lg:grid-cols-3"><div className="rounded-xl border border-emerald-400/10 bg-emerald-400/[.025] p-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-300">Selected</div>{optimized.length?optimized.map(s=><div key={s.id} className="mt-1.5 truncate text-[10px] text-slate-300">✓ {s.shortName} <span className="text-slate-600">{s.odds.toFixed(2)}</span></div>):<div className="mt-1 text-[10px] text-slate-500">No selection survived constraints.</div>}</div><div className="rounded-xl border border-red-400/10 bg-red-400/[.025] p-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-red-300">Rejected · WHY</div>{rejected.length?rejected.map(x=><div key={x.selection.id} className="mt-1.5"><div className="truncate text-[10px] text-slate-300">✕ {x.selection.shortName}</div><div className="text-[9px] leading-relaxed text-red-200/60">{x.reason}</div></div>):<div className="mt-1 text-[10px] text-slate-500">No explicit optimizer rejection reason.</div>}</div><div className="rounded-xl border border-violet-400/10 bg-violet-400/[.025] p-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-violet-300">What changes</div>{removed.length?removed.map(s=><div key={s.id} className="mt-1.5 text-[10px] text-slate-300">→ Remove {s.shortName}</div>):<div className="mt-1 text-[10px] text-slate-500">No removals. Optimizer keeps the submitted set.</div>}<div className="mt-2 border-t border-white/5 pt-2 text-[9px] text-slate-600">Target: {optimization.selections.length} leg(s) · diversification {pct(optimization.diversificationScore)}</div></div></div>:null}
  {optimization?<div className="mx-4 mb-4 rounded-xl border border-violet-400/25 bg-gradient-to-r from-violet-500/[.10] to-transparent p-4 shadow-[0_0_45px_rgba(124,92,255,.08)] md:mx-5 md:mb-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-violet-300">Optimized coupon</div><div className="mt-1 text-[10px] text-slate-500">Engine output after active portfolio constraints.</div></div><div className="text-right"><div className="text-2xl font-black tracking-tight text-white">{optimization.combinedOdds.toFixed(2)}</div><div className="text-[9px] uppercase tracking-wider text-slate-600">{optimization.selections.length} legs</div></div></div><div className="mt-3 flex flex-wrap gap-1.5">{optimized.map(s=><span key={s.id} className="rounded-lg border border-violet-400/20 bg-violet-400/10 px-2.5 py-1.5 text-[9px] font-bold text-violet-100">{s.shortName} · {s.odds.toFixed(2)}</span>)}</div></div>:null}
  <details className="border-t border-white/[.07] px-4 py-3 md:px-5"><summary className="cursor-pointer text-[9px] font-black uppercase tracking-[.18em] text-slate-500 transition hover:text-slate-300">Decision trace</summary><div className="mt-2 space-y-1">{result.trace.map(x=><div key={x} className="font-mono text-[9px] text-slate-600">› {x}</div>)}</div></details>
 </section>;
}
