export type StageStatus='IMPLEMENTED'|'VALIDATED_NEXT';
export interface MonetizationStage { id:string; title:string; status:StageStatus; acceptance:string[]; }
const S=(id:string,title:string,acceptance:string[]):MonetizationStage=>({id,title,status:'IMPLEMENTED',acceptance});
export const M45_M100:MonetizationStage[]=[
S('M45','Risk Policy Contract',['CLEAR/REVIEW/BLOCKED']),S('M46','Policy Decision Engine',['deterministic policy decision']),S('M47','Evidence Quality Engine',['freshness/source/confidence']),S('M48','Correlation & Exposure Engine',['event/market/correlation exposure']),S('M49','Human Approval Gate 2.0',['approval remains separate']),S('M50','Approval Audit Trail',['decision trace']),
S('M51','Execution Permission Contract',['approval != permission']),S('M52','Permission Evaluator',['policy/data/risk/mode gates']),S('M53','Execution Mode Controller',['observational default']),S('M54','Execution Safety',['stale/duplicate/kill-switch concepts']),S('M55','Execution Event Ledger',['event contract']),S('M56','Full Gate Verification',['gate tests']),
S('M57','Outcome Engine',['PENDING/WON/LOST/PUSH/VOID']),S('M58','Prediction Grading',['hit-rate/Brier/ROI']),S('M59','Model Performance',['sport/market/model dimensions']),S('M60','Calibration Engine',['probability calibration']),S('M61','Learning Engine',['outcome -> learning']),S('M62','Memory Engine',['historical record contract']),S('M63','Model Versioning',['modelVersion on prediction']),S('M64','Public Performance Ledger',['immutable track record']),
S('M65','Prediction Engine',['probability/fair odds/edge/EV']),S('M66','Ensemble Engine',['multi-signal architecture contract']),S('M67','Probability Engine',['probability distinct from confidence']),S('M68','Confidence Engine',['confidence field and gates']),S('M69','Edge Engine',['model vs implied']),S('M70','Line Movement Engine',['market movement contract']),S('M71','Closing Line Benchmark',['benchmark contract']),S('M72','Prediction Explanation',['why + failure mode']),
S('M73','User Accounts',['plan identity boundary']),S('M74','User Profile',['profile boundary']),S('M75','Favourite Sports',['preference contract']),S('M76','Favourite Leagues',['preference contract']),S('M77','Prediction Watchlist',['watchlist boundary']),S('M78','Alerts',['alert entitlement boundary']),S('M79','Personal Dashboard',['user KPI boundary']),S('M80','Personal Learning',['personal performance boundary']),
S('M81','Subscription Engine',['monthly/annual/trial states']),S('M82','Plan Entitlements',['server-side plan contract']),S('M83','Free -> Pro',['upgrade path']),S('M84','Trial',['trial lifecycle']),S('M85','Coupon/Promo',['promotion contract']),S('M86','Founder Pricing',['12-month founder pass']),S('M87','Annual Billing',['annual pricing']),S('M88','One-Time Products',['day/season/founder contract']),S('M89','Refund/Cancellation',['billing lifecycle']),S('M90','Revenue Analytics',['MRR/ARR/ARPU/churn']),
S('M91','Checkout Contract',['provider-neutral server boundary']),S('M92','Billing Webhook Contract',['payment event boundary']),S('M93','Landing/Product Positioning',['analytics-first positioning']),S('M94','Interactive Demo',['value before paywall']),S('M95','Prediction Detail',['evidence/result surface']),S('M96','Model Evidence',['methodology surface']),S('M97','Pricing',['Free/Pro/Quant/Analyst']),S('M98','Funnel Analytics',['activation/conversion/retention']),S('M99','Production Security',['security/availability gate']),S('M100','Monetization Go-Live',['all commercial gates required'])
];
export function getStage(id:string){return M45_M100.find(s=>s.id===id);}
